# Generated by Django 4.2.18 on 2025-03-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='introduction',
            field=models.CharField(blank=True, default='这个家伙很懒，还没有添加简介~~', max_length=400),
        ),
    ]
