# Generated by Django 5.2.4 on 2025-07-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_bannedip_requestlog_banneduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consecutive_check_in_days',
            field=models.PositiveIntegerField(default=0, verbose_name='连续签到天数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次签到时间'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='用户等级'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='用户积分'),
        ),
    ]
