# Generated by Django 4.2.18 on 2025-04-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_banneduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('ban_end_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='user',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
    ]
