# Generated by Django 5.2.4 on 2025-07-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_consecutive_check_in_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='EULA_read',
            field=models.BooleanField(default=False, verbose_name='是否已阅读用户须知'),
        ),
    ]
