services:
  - type: web
    name: your-web-service
    runtime: python  # 根据项目类型选择 runtime（如 node、python、ruby 等）
    buildCommand: pip install -r requirements.txt  # 安装依赖
    startCommand: python manage.py runserver 0.0.0.0:8000 # 启动命令
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "sdsyxyq.onrender.com"
