# Generated by Django 4.2.18 on 2025-03-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyq_files', '0005_alter_entry_owner_alter_reply_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
