# Generated by Django 4.2.18 on 2025-03-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyq_files', '0006_entry_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
